tickers:
  poland:
    FOR.WA: "Forbo"
    MRC.WA: "Mirbud"
  europe:
    OR.PA: "L'Oreal"
    CS.PA: "AXA"
  usa:
    BA: "Boeing"
    CAT: "Caterpillar"
  global:
    FMX: "FEMSA"
    TATAMOTORS.NS: "Tata Motors"
    NSRGY: "Nestle"
    SQM: "Sociedad Quimica y Minera de Chile"
