active_profile_path: config\runtime_profiles\Gen6_1__group__bbva_peer_banks.yaml
profiles:
  Gen6_1__single__BBVA_MC:
    model_name: Gen6_1__single__BBVA_MC
    base_model_name: Gen6_1
    profile_path: config\runtime_profiles\Gen6_1__single__BBVA_MC.yaml
    label: 'Ticker unico: BBVA.MC'
    description: ''
    notes: ''
    universe_mode: single_ticker
    single_ticker_symbol: BBVA.MC
    predefined_group_name: null
    requested_tickers:
    - BBVA.MC
    downloaded_tickers:
    - BBVA.MC
    discarded_tickers: []
    final_tickers_used:
    - BBVA.MC
    created_at: '2026-03-22T17:51:49'
    last_trained_at: '2026-03-22T17:51:49'
    prediction_horizon: 60
    years: 3
  Gen6_1__group__bbva_peer_banks:
    model_name: Gen6_1__group__bbva_peer_banks
    base_model_name: Gen6_1
    profile_path: config\runtime_profiles\Gen6_1__group__bbva_peer_banks.yaml
    label: BBVA + peer set bancario curado
    description: Universo bancario europeo curado para entrenar BBVA frente a peers
      comparables.
    notes: Incluye bancos espanoles y peers europeos liquidos para un modelo sectorial
      acotado.
    universe_mode: predefined_group
    single_ticker_symbol: null
    predefined_group_name: bbva_peer_banks
    requested_tickers:
    - BBVA.MC
    - SAN.MC
    - CABK.MC
    - SAB.MC
    - BKT.MC
    - BNP.PA
    - GLE.PA
    - ISP.MI
    - UCG.MI
    - INGA.AS
    downloaded_tickers:
    - BBVA.MC
    - SAN.MC
    - CABK.MC
    - SAB.MC
    - BKT.MC
    - BNP.PA
    - GLE.PA
    - ISP.MI
    - UCG.MI
    - INGA.AS
    discarded_tickers: []
    final_tickers_used:
    - BBVA.MC
    - BKT.MC
    - BNP.PA
    - CABK.MC
    - GLE.PA
    - INGA.AS
    - ISP.MI
    - SAB.MC
    - SAN.MC
    - UCG.MI
    created_at: '2026-03-22T20:25:05'
    last_trained_at: '2026-03-22T20:25:05'
    prediction_horizon: 60
    years: 3
