tickers:
  poland:
    FOR.WA: "Forbo"
    MRC.WA: "Mirbud"
  europe:
    BBVA.MC: "Banco Bilbao Vizcaya Argentaria"
    SAN.MC: "Banco Santander"
    CABK.MC: "CaixaBank"
    SAB.MC: "Banco Sabadell"
    BKT.MC: "Bankinter"
    BNP.PA: "BNP Paribas"
    GLE.PA: "Societe Generale"
    ISP.MI: "Intesa Sanpaolo"
    UCG.MI: "UniCredit"
    INGA.AS: "ING Groep"
    OR.PA: "L'Oreal"
    CS.PA: "AXA"
  usa:
    AAPL: "Apple Inc."
    MSFT: "Microsoft Corporation"
    NVDA: "NVIDIA"
    TSLA: "Tesla, Inc."
    BA: "Boeing"
    CAT: "Caterpillar"
  global:
    FMX: "FEMSA"
    TATAMOTORS.NS: "Tata Motors"
    NSRGY: "Nestle"
    SQM: "Sociedad Quimica y Minera de Chile"
